- lib/DashboardManager.js
- package.json
remove ranking and music metrics from package.json and dashboard api
> Plug 29 - remove ranking and music metrics 

- lib/Activator.js
- lib/Constants.js
- lib/DashboardManager.js
- lib/KeystrokeManager.js
- lib/UtilManager.js
- lib/managers/EventManager.js
- lib/managers/FileManager.js
- lib/managers/KpmManager.js
- lib/managers/PluginDataManager.js
- lib/managers/ProjectManager.js
- lib/managers/SessionSummaryManager.js
- lib/managers/TimeDataManager.js
- lib/managers/TrackerManager.js
- lib/managers/WallClockManager.js
- lib/managers/WindowManager.js
- lib/model/FileChangeInfo.js
- lib/model/KeystrokeAggregate.js
- lib/model/RepoContributor.js
- lib/model/TeamMember.js
- lib/model/TimeCounterStats.js
- lib/repo/GitUtil.js
- lib/test.txt
- lib/tree/CodeTimeProvider.js
- lib/utils/CommandUtil.js
- lib/utils/EventUtil.js
- package.json
- yarn.lock
this implements the time counter logic and tracker
> timer counter and tracker implementation

- deployer.js
- lib/Activator.js
- lib/KeystrokeManager.js
- lib/KpmStatusView.js
- lib/UtilManager.js
- lib/managers/EventManager.js
- lib/managers/KpmManager.js
- lib/managers/PluginDataManager.js
- lib/managers/StatusManager.js
- lib/managers/TimeDataManager.js
- lib/managers/TrackerManager.js
- lib/test.txt
- lib/tree/CodeTimeProvider.js
- lib/utils/CommandUtil.js
- lib/utils/EventUtil.js
- lib/utils/MenuUtil.js
- package-lock.json
- package.json
- yarn.lock
updated the chars pasted to use the diff and cleaned up the logic to onboard
> updated chars pasted using diff

- lib/tree/CodeTimeProvider.js
and also added two newlines for my ocd because the two conditionals right below it had it on multiple lines
> change keystrokes top files values from kpm to keystrokes

- lib/Activator.js
- lib/DashboardManager.js
- lib/UtilManager.js
- lib/utils/ServiceUtil.js
- package.json
* Make sure we read the setting correctly before setting the interval that gets git data.
* Remove unused editor setting (and related code) for showing rank.
* Remove editor setting (and related code) for showing Git (we will either send or not, but not have an option to show or not)
> Disable Git Data: Do not send git data if flag is true

- lib/UtilManager.js
- lib/managers/TimeDataManager.js
- lib/utils/CommandUtil.js
- package-lock.json
- package.json
content was undefined and threw an exception here
> fix content undefined check

- README.md
- Added new images and descriptions for the Code Anywhere dashboard
- Merge when dashboard goes live
> add dashboard features

- lib/DashboardManager.js
- package.json
change the showToday to true to enable backward compatibility
> omit the today section

- lib/UtilManager.js
- lib/managers/SlackManager.js
- lib/tree/CodeTimeProvider.js
- lib/utils/PopupUtil.js
- styles/swdc-atom.less
- templates/structure-view.html
> fix status input interactions

- lib/managers/SlackManager.js
I'll eventually merge vscode and atom's slack management to ensure vscode gets this fix as well.
also fixed one of the functions that requires the integrations
> fix issue of getting refused to set unsafe header user-agent

- lib/Activator.js
- lib/UserStatusManager.js
- lib/UtilManager.js
- lib/config.js
- lib/managers/ConfigManager.js
- lib/managers/FlowManager.js
- lib/managers/ScreenManager.js
- lib/managers/SlackManager.js
- lib/managers/WindowManager.js
- lib/model/SessionSummary.js
- lib/tree/CodeTimeProvider.js
- lib/tree/ProviderManager.js
- lib/utils/CommandUtil.js
- lib/utils/MenuUtil.js
- lib/utils/PopupUtil.js
- package-lock.json
- package.json
- styles/swdc-atom.less
- templates/structure-view.html
loom:
https://www.loom.com/share/cbb5f91ed0cf4c76a13db5635ae9e83b
humanize minutes update
> flow mode implementation

- lib/Activator.js
- lib/UserStatusManager.js
- lib/managers/SlackManager.js
- lib/utils/ServiceUtil.js
- package.json
- yarn.lock
* send the plugin uuid in the headers
* disconnect slack integrations on authentication instead of all integrations
> add plugin uuid header and use disconnect slack integrations

- lib/UtilManager.js
- lib/managers/PluginDataManager.js
- lib/managers/SessionAppManager.js
- lib/tree/ProviderManager.js
- package.json
- yarn.lock
this checks the global file system flag whether the plugin needs to fetch the session summary data when making the tree view visible
> check whether session summary should be fetched

- lib/Activator.js
- lib/Constants.js
- lib/UserStatusManager.js
- lib/config.js
- lib/managers/ConfigManager.js
- lib/managers/FlowManager.js
- lib/message_handlers/flow_score.js
- lib/tree/CodeTimeProvider.js
- lib/utils/CommandUtil.js
- lib/websockets.js
- package.json
- templates/structure-view.html
- yarn.lock
https://www.loom.com/share/de654682459c4c1fb36542b87beed527
> flow mode reminders and websockets

- README.md
- add teams features
- updated product images
- carry over all changes from VS Code readme
> update readme to include teams features

- lib/Constants.js
- lib/UserStatusManager.js
- lib/UtilManager.js
- lib/managers/OsaScriptManager.js
- lib/managers/SlackManager.js
- lib/message_handlers/authenticated_plugin_user.js
- lib/message_handlers/integration_connection.js
- lib/repo/GitUtil.js
- lib/utils/CommandUtil.js
- lib/utils/ExecUtil.js
- lib/utils/ServiceUtil.js
- lib/websockets.js
- package.json
- yarn.lock
* implements the handlers for the auth completion and integration change events
* centralizes the command exec
* removes unused code
* upgrades npm versions
> impl websocket auth and integration handlers

- lib/Activator.js
- lib/Constants.js
- lib/DashboardManager.js
- lib/UtilManager.js
- lib/managers/FlowManager.js
- lib/managers/PluginDataManager.js
- lib/managers/SessionAppManager.js
- lib/managers/SlackManager.js
- lib/managers/StatusManager.js
- lib/message_handlers/current_day_stats_update.js
- lib/model/SessionSummary.js
- lib/utils/ServiceUtil.js
this will reconcile slack with other types (spotify) of integrations
> app endpoint impl and general cleanup/refactor

- lib/UtilManager.js
- lib/managers/SlackManager.js
- lib/tree/CodeTimeProvider.js
- lib/utils/CommandUtil.js
* migrates the google and github auth endpoints and cleans up slack connect/disconnect
> migrate auth endpoints and slack connect cleanup

- lib/Activator.js
- lib/UtilManager.js
- lib/utils/ServiceUtil.js
- package.json
this migrates the anon api to v1 api
> migrate onboard apis

- package.json
publish anon api migration update
> Publish 4.4.22
